/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgramsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgramsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgramsController_organizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgramsController_organization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MatchingController_match"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssistantController_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssistantController_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DemoController_persona"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgController_drafts"];
        put?: never;
        post: operations["OrgController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @example ok */
            status: string;
        };
        LocalizedTextDto: {
            uz?: string;
            ru?: string;
            en?: string;
        };
        OrganizationRefDto: {
            slug: string;
            name: string;
            /** @enum {string} */
            verification: "VERIFIED" | "UNVERIFIED";
        };
        ProgramSummaryDto: {
            id: string;
            title: components["schemas"]["LocalizedTextDto"];
            summary: components["schemas"]["LocalizedTextDto"];
            /** @description Support type vocabulary values */
            supportTypes: string[];
            genders: string[];
            /** @description Document vocabulary values */
            requiredDocuments: string[];
            /** @enum {string} */
            applicationStatus: "OPEN" | "CLOSED" | "UNKNOWN";
            /** Format: date-time */
            deadline: string | null;
            /** Format: date-time */
            statusVerifiedAt: string | null;
            isDraft: boolean;
            /**
             * @description SAMPLE = invented prototype data; RESEARCHED = collected from a public source
             * @enum {string}
             */
            origin: "SAMPLE" | "RESEARCHED";
            /** @description Page the program information was collected from */
            sourceUrl: string | null;
            /** @description Region vocabulary values; empty means nationwide */
            regions: string[];
            /** @description Circumstance vocabulary values the program is designed for */
            targetCircumstances: string[];
            organization: components["schemas"]["OrganizationRefDto"];
        };
        ProgramDetailDto: {
            id: string;
            title: components["schemas"]["LocalizedTextDto"];
            summary: components["schemas"]["LocalizedTextDto"];
            /** @description Support type vocabulary values */
            supportTypes: string[];
            genders: string[];
            /** @description Document vocabulary values */
            requiredDocuments: string[];
            /** @enum {string} */
            applicationStatus: "OPEN" | "CLOSED" | "UNKNOWN";
            /** Format: date-time */
            deadline: string | null;
            /** Format: date-time */
            statusVerifiedAt: string | null;
            isDraft: boolean;
            /**
             * @description SAMPLE = invented prototype data; RESEARCHED = collected from a public source
             * @enum {string}
             */
            origin: "SAMPLE" | "RESEARCHED";
            /** @description Page the program information was collected from */
            sourceUrl: string | null;
            /** @description Region vocabulary values; empty means nationwide */
            regions: string[];
            /** @description Circumstance vocabulary values the program is designed for */
            targetCircumstances: string[];
            organization: components["schemas"]["OrganizationRefDto"];
            howToApply?: components["schemas"]["LocalizedTextDto"] | null;
            ageMin: number | null;
            ageMax: number | null;
            requiredCircumstances: string[];
            incomeTested: boolean;
            /** @description Where the information came from */
            source: string;
            /** Format: date-time */
            researchedAt: string | null;
        };
        OrganizationDetailDto: {
            slug: string;
            name: string;
            /** @enum {string} */
            verification: "VERIFIED" | "UNVERIFIED";
            description: components["schemas"]["LocalizedTextDto"];
            categories: string[];
            sections: ("children_family" | "health" | "social_support" | "disability" | "education_youth" | "women_girls" | "food_humanitarian" | "emergency" | "faith_zakat" | "development")[];
            /** @enum {string} */
            kind: "NGO" | "INTERNATIONAL" | "GOVERNMENT";
            website: string | null;
            phone: string | null;
            email: string | null;
            source: string;
            sourceUrl: string | null;
            /**
             * Format: date-time
             * @description When information was collected from sourceUrl
             */
            researchedAt: string | null;
            /** Format: date-time */
            lastVerifiedAt: string | null;
            programs: components["schemas"]["ProgramSummaryDto"][];
        };
        SupportProfileDto: {
            needs: ("financial" | "education" | "food" | "health" | "maternity" | "children_family" | "employment" | "business" | "housing" | "legal" | "safety" | "disability" | "mental_wellbeing" | "emergency")[];
            /** @enum {string} */
            region?: "tashkent_city" | "tashkent_region" | "andijan" | "bukhara" | "fergana" | "jizzakh" | "kashkadarya" | "khorezm" | "namangan" | "navoi" | "samarkand" | "surkhandarya" | "syrdarya" | "karakalpakstan";
            ageMin?: number;
            ageMax?: number;
            /** @enum {string} */
            gender?: "female" | "male";
            childrenCount?: number;
            circumstances: ("student" | "employed" | "unemployed" | "single_parent" | "has_children" | "pregnant" | "disability" | "low_income" | "entrepreneur" | "survivor" | "care_leaver")[];
            notCircumstances: ("student" | "employed" | "unemployed" | "single_parent" | "has_children" | "pregnant" | "disability" | "low_income" | "entrepreneur" | "survivor" | "care_leaver")[];
        };
        MatchFiltersDto: {
            onlyOpen?: boolean;
            womenOnly?: boolean;
        };
        MatchRequestDto: {
            profile: components["schemas"]["SupportProfileDto"];
            filters?: components["schemas"]["MatchFiltersDto"];
        };
        MatchReasonDto: {
            /** @enum {string} */
            kind: "yes" | "unknown" | "risk";
            /** @description i18n key under "reasons." in the web app */
            key: string;
            params?: {
                [key: string]: string;
            };
        };
        MatchResultDto: {
            program: components["schemas"]["ProgramSummaryDto"];
            /** @enum {string} */
            fit: "strong" | "possible" | "needs_info";
            reasons: components["schemas"]["MatchReasonDto"][];
        };
        AssistantInfoDto: {
            /** @description Whether the AI-assisted (Gemini) mode is configured on this server */
            aiAvailable: boolean;
        };
        HistoryItemDto: {
            /** @enum {string} */
            role: "user" | "model";
            text: string;
        };
        AssistantStateDto: {
            profile: components["schemas"]["SupportProfileDto"];
            /** @enum {string} */
            mode: "chat" | "results" | "safety";
            asked: ("need" | "region" | "age" | "situation")[];
            retried: ("need" | "region" | "age" | "situation")[];
            /** @enum {string} */
            pendingSlot?: "need" | "region" | "age" | "situation";
            filters: components["schemas"]["MatchFiltersDto"];
            lastResultIds: string[];
            turn: number;
            /** @description Recent turns, for the LLM engine */
            history?: components["schemas"]["HistoryItemDto"][];
        };
        AssistantChoiceDto: {
            /** @enum {string} */
            slot: "need" | "region" | "age" | "situation" | "safety" | "next";
            values: string[];
        };
        AssistantTurnRequestDto: {
            /** @description Omit to start a new conversation */
            state?: components["schemas"]["AssistantStateDto"];
            text?: string;
            /**
             * @description Language the assistant should answer in
             * @enum {string}
             */
            locale?: "uz" | "ru" | "en";
            choice?: components["schemas"]["AssistantChoiceDto"];
            /**
             * @description "private" never sends the turn to a language model (scripted engine only). Defaults to "ai".
             * @enum {string}
             */
            assistantMode?: "ai" | "private";
        };
        AssistantMessageDto: {
            /** @description i18n key under "assistant." in the web app ("llm" when `text` is set) */
            key: string;
            /** @description Free text from the Gemini engine, already in the requested language */
            text?: string;
            params?: {
                [key: string]: string | number;
            };
            list?: string[];
            /** @enum {string} */
            listKind?: "need" | "document" | "circumstance";
            programId?: string;
        };
        QuickReplyOptionDto: {
            value: string;
            /** @description i18n key under "assistant." in the web app */
            labelKey: string;
            href?: string;
        };
        QuickRepliesDto: {
            /** @enum {string} */
            slot: "need" | "region" | "age" | "situation" | "safety" | "next";
            multi: boolean;
            options: components["schemas"]["QuickReplyOptionDto"][];
        };
        AssistantTurnResponseDto: {
            state: components["schemas"]["AssistantStateDto"];
            /**
             * @description Which assistant engine produced this turn
             * @enum {string}
             */
            engine: "gemini" | "scripted";
            messages: components["schemas"]["AssistantMessageDto"][];
            quickReplies?: components["schemas"]["QuickRepliesDto"];
            /** @description Present when the assistant shows results */
            results?: components["schemas"]["MatchResultDto"][];
        };
        DemoDocumentDto: {
            /** @description Document vocabulary value */
            type: string;
            /** @enum {string} */
            status: "ready" | "missing";
        };
        DemoApplicationDto: {
            id: string;
            program: components["schemas"]["ProgramSummaryDto"];
            /** @enum {string} */
            status: "not_started" | "in_progress" | "submitted";
            /** @description Percent of application steps done (requirements, documents, statement) */
            progress: number;
            readyDocuments: string[];
            missingDocuments: string[];
        };
        DemoPersonaDto: {
            /** @description Always true — this is fixed demonstration data, not a real account */
            isDemo: boolean;
            name: string;
            profile: components["schemas"]["SupportProfileDto"];
            documents: components["schemas"]["DemoDocumentDto"][];
            applications: components["schemas"]["DemoApplicationDto"][];
            /** @description Matches for the persona not already applied to */
            recommendations: components["schemas"]["MatchResultDto"][];
        };
        CreateProgramDto: {
            orgSlug: string;
            /**
             * @description Language the title and description are written in
             * @enum {string}
             */
            locale: "uz" | "ru" | "en";
            title: string;
            summary: string;
            supportTypes: ("financial" | "education" | "food" | "health" | "maternity" | "children_family" | "employment" | "business" | "housing" | "legal" | "safety" | "disability" | "mental_wellbeing" | "emergency")[];
            /** @description Empty = anyone */
            genders: ("female" | "male")[];
            ageMin?: number;
            ageMax?: number;
            /** @description Empty = nationwide */
            regions: ("tashkent_city" | "tashkent_region" | "andijan" | "bukhara" | "fergana" | "jizzakh" | "kashkadarya" | "khorezm" | "namangan" | "navoi" | "samarkand" | "surkhandarya" | "syrdarya" | "karakalpakstan")[];
            requiredDocuments: ("id_document" | "income_certificate" | "enrollment_certificate" | "birth_certificate" | "medical_report" | "disability_certificate" | "residence_certificate" | "business_plan" | "family_composition")[];
            /** @enum {string} */
            applicationStatus: "OPEN" | "CLOSED" | "UNKNOWN";
            /** Format: date */
            deadline?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    ProgramsController_list: {
        parameters: {
            query?: {
                supportType?: "financial" | "education" | "food" | "health" | "maternity" | "children_family" | "employment" | "business" | "housing" | "legal" | "safety" | "disability" | "mental_wellbeing" | "emergency";
                region?: "tashkent_city" | "tashkent_region" | "andijan" | "bukhara" | "fergana" | "jizzakh" | "kashkadarya" | "khorezm" | "namangan" | "navoi" | "samarkand" | "surkhandarya" | "syrdarya" | "karakalpakstan";
                /** @description Only programs currently accepting applications */
                open?: boolean;
                /** @description Organization slug */
                org?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummaryDto"][];
                };
            };
        };
    };
    ProgramsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDetailDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgramsController_organizations: {
        parameters: {
            query?: {
                section?: "children_family" | "health" | "social_support" | "disability" | "education_youth" | "women_girls" | "food_humanitarian" | "emergency" | "faith_zakat" | "development";
                /** @description Case-insensitive name search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailDto"][];
                };
            };
        };
    };
    ProgramsController_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MatchingController_match: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResultDto"][];
                };
            };
        };
    };
    AssistantController_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantInfoDto"];
                };
            };
        };
    };
    AssistantController_turn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantTurnRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantTurnResponseDto"];
                };
            };
        };
    };
    DemoController_persona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoPersonaDto"];
                };
            };
        };
    };
    OrgController_drafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDetailDto"][];
                };
            };
        };
    };
    OrgController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProgramDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDetailDto"];
                };
            };
        };
    };
}
