/**
 * Organization directory, imported from the Hamroh team's list "O‘zbekistondagi xayriya, fond va
 * yordam tashkilotlari — 100 ta nom" (tran.docx, received 23 Sep 2026). The list has 100 numbered
 * entries across 10 sections; organizations listed in several sections are merged here (69 unique).
 *
 * The source gives names only. Nothing here has been verified: no descriptions, contacts or programs
 * are invented. `kind` is our classification — PARTNER and GROUPING entries are kept for reference but
 * hidden from people (they fund organizations or aren't a single organization). `listNumbers` are the
 * entry numbers in the source list, for tracing back.
 *
 * Regenerate by editing this file; the seed merges it into existing organizations by slug.
 */
export type DirectoryKind = 'NGO' | 'INTERNATIONAL' | 'GOVERNMENT' | 'PARTNER' | 'GROUPING';

export interface DirectoryEntry {
  slug: string;
  name: string;
  sections: string[];
  kind: DirectoryKind;
  listNumbers: number[];
}

export const DIRECTORY_SOURCE = 'Hamroh organization list (Sep 2026) — name only, not yet checked';

/** Source-list section → support types used by matching and filters. */
export const SECTION_SUPPORT_TYPES: Record<string, string[]> = {
  children_family: ['children_family'],
  health: ['health'],
  social_support: ['financial'],
  disability: ['disability'],
  education_youth: ['education'],
  women_girls: [],
  food_humanitarian: ['food'],
  emergency: ['emergency'],
  faith_zakat: ['financial'],
  development: [],
};

export const directory: DirectoryEntry[] = [
  {
    slug: 'bolalarni-qollab-quvvatlash-jamoat-fondi',
    name: 'Bolalarni qo‘llab-quvvatlash jamoat fondi',
    sections: ['children_family'],
    kind: 'NGO',
    listNumbers: [1],
  },
  {
    slug: 'ona-fondi',
    name: 'ONA Fondi',
    sections: ['children_family', 'women_girls'],
    kind: 'NGO',
    listNumbers: [2, 51],
  },
  {
    slug: 'sen-yolgiz-emassan-jamgarmasi',
    name: '“Sen yolg‘iz emassan” jamg‘armasi',
    sections: ['children_family', 'disability'],
    kind: 'NGO',
    listNumbers: [3, 40],
  },
  {
    slug: 'sos-ozbekiston-bolalar-mahallalari',
    name: 'SOS O‘zbekiston Bolalar Mahallalari',
    sections: ['children_family'],
    kind: 'INTERNATIONAL',
    listNumbers: [4],
  },
  {
    slug: 'bolalarni-ijtimoiy-moslashtirish-respublika-markazi',
    name: 'Bolalarni ijtimoiy moslashtirish Respublika markazi',
    sections: ['children_family'],
    kind: 'GOVERNMENT',
    listNumbers: [5],
  },
  {
    slug: 'ozbekiston-maxsus-olimpiadasi',
    name: 'O‘zbekiston Maxsus Olimpiadasi',
    sections: ['children_family', 'disability'],
    kind: 'NGO',
    listNumbers: [6, 35],
  },
  {
    slug: 'bolalar-va-oilalarni-qollab-quvvatlash-assotsiatsiyasi',
    name: 'Bolalar va oilalarni qo‘llab-quvvatlash assotsiatsiyasi',
    sections: ['children_family'],
    kind: 'NGO',
    listNumbers: [7],
  },
  {
    slug: 'ezgu-amal-jamgarmasi',
    name: '“Ezgu Amal” jamg‘armasi',
    sections: ['children_family', 'health'],
    kind: 'NGO',
    listNumbers: [8, 13],
  },
  {
    slug: 'mehribonlik-jamgarmasi',
    name: '“Mehribonlik” jamg‘armasi',
    sections: ['children_family'],
    kind: 'NGO',
    listNumbers: [9],
  },
  {
    slug: 'bolalar-mahallasi-jamgarmasi',
    name: '“Bolalar Mahallasi” jamg‘armasi',
    sections: ['children_family'],
    kind: 'NGO',
    listNumbers: [10],
  },
  {
    slug: 'mirabror-usmonov-xalqaro-xayriya-jamoat-fondi',
    name: 'Mirabror Usmonov xalqaro xayriya jamoat fondi',
    sections: ['health'],
    kind: 'NGO',
    listNumbers: [11],
  },
  {
    slug: 'soglom-avlod',
    name: '“Sog‘lom avlod uchun” xalqaro xayriya fondi',
    sections: ['health', 'women_girls'],
    kind: 'NGO',
    listNumbers: [12, 52],
  },
  {
    slug: 'nanasaid-jamoat-fondi',
    name: '“Nana’Said” jamoat fondi',
    sections: ['health'],
    kind: 'NGO',
    listNumbers: [14],
  },
  {
    slug: 'red-crescent-uz',
    name: 'O‘zbekiston Qizil Yarim Oy jamiyati',
    sections: ['health', 'social_support', 'food_humanitarian', 'emergency'],
    kind: 'NGO',
    listNumbers: [15, 28, 61, 71],
  },
  {
    slug: 'chegarasiz-shifokorlar',
    name: '“Chegarasiz shifokorlar”',
    sections: ['health', 'emergency'],
    kind: 'INTERNATIONAL',
    listNumbers: [16, 77],
  },
  {
    slug: 'vaqf-xayriya-jamoat-fondi',
    name: '“Vaqf” xayriya jamoat fondi',
    sections: ['health', 'social_support', 'food_humanitarian', 'faith_zakat'],
    kind: 'NGO',
    listNumbers: [17, 27, 62, 81],
  },
  {
    slug: 'zamin',
    name: '“Zamin” fondi',
    sections: ['health', 'disability', 'education_youth', 'women_girls'],
    kind: 'NGO',
    listNumbers: [18, 39, 42, 54],
  },
  {
    slug: 'salomatlik-jamgarmasi',
    name: '“Salomatlik” jamg‘armasi',
    sections: ['health'],
    kind: 'NGO',
    listNumbers: [19],
  },
  {
    slug: 'mehrli-qollar-markazi',
    name: '“Mehrli Qo‘llar” markazi',
    sections: ['health', 'disability'],
    kind: 'NGO',
    listNumbers: [20, 38],
  },
  {
    slug: 'saxovat-va-komak-jamgarmasi',
    name: '“Saxovat va ko‘mak” jamg‘armasi',
    sections: ['social_support', 'food_humanitarian'],
    kind: 'NGO',
    listNumbers: [21, 64],
  },
  {
    slug: 'mahalla-xayriya-jamoat-fondi',
    name: '“Mahalla” xayriya jamoat fondi',
    sections: ['social_support', 'food_humanitarian'],
    kind: 'NGO',
    listNumbers: [22, 63],
  },
  {
    slug: 'muruvvat-jamgarmasi',
    name: '“Muruvvat” jamg‘armasi',
    sections: ['social_support'],
    kind: 'NGO',
    listNumbers: [23],
  },
  {
    slug: 'ijtimoiy-himoya-milliy-agentligi',
    name: 'Ijtimoiy himoya milliy agentligi',
    sections: ['social_support'],
    kind: 'GOVERNMENT',
    listNumbers: [24],
  },
  {
    slug: 'baraka-ijtimoiy-xizmatlar-platformasi',
    name: '“Baraka” ijtimoiy xizmatlar platformasi',
    sections: ['social_support'],
    kind: 'NGO',
    listNumbers: [25],
  },
  {
    slug: 'mehr-nuri',
    name: '“Mehr Nuri” jamg‘armasi',
    sections: ['social_support', 'women_girls'],
    kind: 'NGO',
    listNumbers: [26, 55],
  },
  {
    slug: 'fuqarolik-jamiyati-institutlarini-qollab-quvvatlash-jamoat-fondi',
    name: 'Fuqarolik jamiyati institutlarini qo‘llab-quvvatlash jamoat fondi',
    sections: ['social_support'],
    kind: 'PARTNER',
    listNumbers: [29],
  },
  {
    slug: 'oznntma',
    name: 'O‘zNNTMA — O‘zbekiston nodavlat notijorat tashkilotlari milliy assotsiatsiyasi',
    sections: ['social_support', 'development'],
    kind: 'PARTNER',
    listNumbers: [30, 100],
  },
  {
    slug: 'disability-society-uz',
    name: 'O‘zbekiston nogironlar jamiyati',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [31],
  },
  {
    slug: 'sharoit-plus',
    name: 'SHAROIT PLUS',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [32],
  },
  {
    slug: 'ozbekiston-kozi-ojizlar-jamiyati',
    name: 'O‘zbekiston Ko‘zi ojizlar jamiyati',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [33],
  },
  {
    slug: 'ozbekiston-karlar-jamiyati',
    name: 'O‘zbekiston Karlar jamiyati',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [34],
  },
  {
    slug: 'ozbekiston-nogironlar-aravachasi-assotsiatsiyasi',
    name: 'O‘zbekiston Nogironlar aravachasi assotsiatsiyasi',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [36],
  },
  {
    slug: 'inklyuziv-jamiyat-fondi',
    name: 'Inklyuziv jamiyat fondi',
    sections: ['disability'],
    kind: 'NGO',
    listNumbers: [37],
  },
  {
    slug: 'el-yurt-umidi-jamgarmasi',
    name: '“El-yurt umidi” jamg‘armasi',
    sections: ['education_youth'],
    kind: 'GOVERNMENT',
    listNumbers: [41],
  },
  {
    slug: 'ozbekiston-yoshlar-ittifoqi',
    name: 'O‘zbekiston Yoshlar ittifoqi',
    sections: ['education_youth'],
    kind: 'GOVERNMENT',
    listNumbers: [43],
  },
  {
    slug: 'ozbekiston-volontyorlar-assotsiatsiyasi',
    name: 'O‘zbekiston Volontyorlar assotsiatsiyasi',
    sections: ['education_youth'],
    kind: 'NGO',
    listNumbers: [44],
  },
  {
    slug: 'unesco-ozbekiston',
    name: 'UNESCO O‘zbekiston',
    sections: ['education_youth', 'development'],
    kind: 'PARTNER',
    listNumbers: [45, 96],
  },
  {
    slug: 'unicef-uz',
    name: 'UNICEF O‘zbekiston',
    sections: ['education_youth', 'emergency', 'development'],
    kind: 'INTERNATIONAL',
    listNumbers: [46, 74, 92],
  },
  {
    slug: 'jahon-banki',
    name: 'Jahon banki',
    sections: ['education_youth', 'development'],
    kind: 'PARTNER',
    listNumbers: [47, 99],
  },
  {
    slug: 'osiyo-taraqqiyot-banki',
    name: 'Osiyo taraqqiyot banki',
    sections: ['education_youth', 'development'],
    kind: 'PARTNER',
    listNumbers: [48, 98],
  },
  {
    slug: 'british-council-ozbekiston',
    name: 'British Council O‘zbekiston',
    sections: ['education_youth'],
    kind: 'INTERNATIONAL',
    listNumbers: [49],
  },
  {
    slug: 'erasmus-plus-ozbekiston',
    name: 'Erasmus+ O‘zbekiston',
    sections: ['education_youth'],
    kind: 'INTERNATIONAL',
    listNumbers: [50],
  },
  {
    slug: 'un-women-uz',
    name: 'UN Women O‘zbekiston',
    sections: ['women_girls'],
    kind: 'INTERNATIONAL',
    listNumbers: [53],
  },
  {
    slug: 'istiqbolli-avlod',
    name: '“Istiqbolli Avlod” ijtimoiy-axborot markazi',
    sections: ['women_girls'],
    kind: 'NGO',
    listNumbers: [56],
  },
  {
    slug: 'gender-tengligi-markazi',
    name: 'Gender tengligi markazi',
    sections: ['women_girls'],
    kind: 'NGO',
    listNumbers: [57],
  },
  {
    slug: 'tadbirkor-ayol',
    name: 'O‘zbekiston Ayol tadbirkorlar assotsiatsiyasi',
    sections: ['women_girls'],
    kind: 'NGO',
    listNumbers: [58],
  },
  {
    slug: 'ayollar-tadbirkorligini-qollab-quvvatlash-fondi',
    name: 'Ayollar tadbirkorligini qo‘llab-quvvatlash fondi',
    sections: ['women_girls'],
    kind: 'NGO',
    listNumbers: [59],
  },
  {
    slug: 'ayollarni-qollab-quvvatlash-tashkilotlari',
    name: 'Ayollarni qo‘llab-quvvatlash tashkilotlari',
    sections: ['women_girls'],
    kind: 'GROUPING',
    listNumbers: [60],
  },
  {
    slug: 'ozbekiston-musulmonlari-idorasi',
    name: 'O‘zbekiston musulmonlari idorasi',
    sections: ['food_humanitarian', 'faith_zakat'],
    kind: 'NGO',
    listNumbers: [65, 82],
  },
  {
    slug: 'islom-taraqqiyot-banki',
    name: 'Islom taraqqiyot banki',
    sections: ['food_humanitarian', 'faith_zakat'],
    kind: 'PARTNER',
    listNumbers: [66, 84],
  },
  {
    slug: 'jahon-oziq-ovqat-dasturi',
    name: 'Jahon oziq-ovqat dasturi',
    sections: ['food_humanitarian', 'emergency'],
    kind: 'INTERNATIONAL',
    listNumbers: [67, 76],
  },
  {
    slug: 'action-against-hunger',
    name: 'Action Against Hunger',
    sections: ['food_humanitarian'],
    kind: 'INTERNATIONAL',
    listNumbers: [68],
  },
  {
    slug: 'care-international',
    name: 'CARE International',
    sections: ['food_humanitarian', 'emergency'],
    kind: 'INTERNATIONAL',
    listNumbers: [69, 80],
  },
  {
    slug: 'mercy-corps-dasturlari',
    name: 'Mercy Corps dasturlari',
    sections: ['food_humanitarian'],
    kind: 'INTERNATIONAL',
    listNumbers: [70],
  },
  {
    slug: 'xalqaro-qizil-xoch-qomitasi',
    name: 'Xalqaro Qizil Xoch Qo‘mitasi',
    sections: ['emergency'],
    kind: 'INTERNATIONAL',
    listNumbers: [72],
  },
  {
    slug: 'bmtning-gumanitar-masalalarni-muvofiqlashtirish-boshqarmasi',
    name: 'BMTning Gumanitar masalalarni muvofiqlashtirish boshqarmasi',
    sections: ['emergency'],
    kind: 'PARTNER',
    listNumbers: [73],
  },
  {
    slug: 'undp-ozbekiston',
    name: 'UNDP O‘zbekiston',
    sections: ['emergency', 'development'],
    kind: 'PARTNER',
    listNumbers: [75, 91],
  },
  {
    slug: 'islamic-relief',
    name: 'Islamic Relief',
    sections: ['emergency', 'faith_zakat'],
    kind: 'INTERNATIONAL',
    listNumbers: [78, 85],
  },
  {
    slug: 'save-the-children',
    name: 'Save the Children',
    sections: ['emergency'],
    kind: 'INTERNATIONAL',
    listNumbers: [79],
  },
  {
    slug: 'zakot-jamgarmalari',
    name: 'Zakot jamg‘armalari',
    sections: ['faith_zakat'],
    kind: 'GROUPING',
    listNumbers: [83],
  },
  {
    slug: 'human-appeal',
    name: 'Human Appeal',
    sections: ['faith_zakat'],
    kind: 'INTERNATIONAL',
    listNumbers: [86],
  },
  {
    slug: 'qatar-charity-dasturlari',
    name: 'Qatar Charity dasturlari',
    sections: ['faith_zakat'],
    kind: 'INTERNATIONAL',
    listNumbers: [87],
  },
  {
    slug: 'turkiya-diyanet-jamgarmasi-dasturlari',
    name: 'Turkiya Diyanet jamg‘armasi dasturlari',
    sections: ['faith_zakat'],
    kind: 'INTERNATIONAL',
    listNumbers: [88],
  },
  {
    slug: 'quvayt-xayriya-dasturlari',
    name: 'Quvayt xayriya dasturlari',
    sections: ['faith_zakat'],
    kind: 'GROUPING',
    listNumbers: [89],
  },
  {
    slug: 'saudiya-arabistoni-xayriya-dasturlari',
    name: 'Saudiya Arabistoni xayriya dasturlari',
    sections: ['faith_zakat'],
    kind: 'GROUPING',
    listNumbers: [90],
  },
  {
    slug: 'unhcr-markaziy-osiyo',
    name: 'UNHCR Markaziy Osiyo',
    sections: ['development'],
    kind: 'INTERNATIONAL',
    listNumbers: [93],
  },
  {
    slug: 'iom-ozbekiston',
    name: 'IOM O‘zbekiston',
    sections: ['development'],
    kind: 'INTERNATIONAL',
    listNumbers: [94],
  },
  {
    slug: 'who-ozbekiston',
    name: 'WHO O‘zbekiston',
    sections: ['development'],
    kind: 'PARTNER',
    listNumbers: [95],
  },
  {
    slug: 'giz-ozbekiston',
    name: 'GIZ O‘zbekiston',
    sections: ['development'],
    kind: 'PARTNER',
    listNumbers: [97],
  },
];
